# Based on https://github.com/andrewhwanpark/dark-poole

# Setup
title: Andreas Gehrke - software developer and architect
#url: https://test2.agehrke.com/
paginate: 1
baseurl: ""
permalink: pretty

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about

# Specify the author for blog posts
author:
  name: Andreas Gehrke
  url: https://twitter.com/mdo
  email: ag@agehrke.com


# Jekyll config

sass:
  sass_dir: _sass
  style: :compressed


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.m