remote_theme: andrewhwanpark/dark-poole

# Gems
plugins:
  - jekyll-seo-tag # Used by andrewhwanpark/dark-poole
  - jekyll-remote-theme


# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about

# Specify the author for blog posts
author:
  name: Andreas Gehrke
  url: https://twitter.com/mdo
  email: ag@agehrke.com

sass:
  sass_dir: _sass
  style: :compressed
