# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andreas Gehrke
email:
description: >- # this means to ignore newlines until "baseurl:"
  Freelance software architect and developer with a passion for the web and for building long-lasting software solutions
twitter_username: agehrke
github_username: agehrke
minimal_mistakes_skin: dark
search: false # No need for the search feature

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name     : "Andreas Gehrke"
  avatar   : "/assets/Andreas.jpg"
  bio      : "Software architect and .NET developer"
  location : "Copenhagen, Denmark"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ag@agehrke.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.agehrke.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/agehrke"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/agehrke"

footer: # https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-footer

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true ## Dates is nice to have
      read_time: false # No need for reading time calculated
      comments: true
      share: false # Drop the dumb social share links
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Disable the taxonomy/archive pages - https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings
# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
